### ISSUE TITLE
Paypal Direct Payments (UK)  - This transaction cannot be processed. Please enter a valid credit card number

### ISSUE THREAD

**Issue by Cabbit** [activemerchant/active_merchant#2569]
I am having a issue since upgrading Spree::Gateway which once I get down to the nitty gritty appears to be some sort of issue with ActiveMerchant. 

I am making a credit card payment with both live and test credit cards and in every case receive this error when running it 'This transaction cannot be processed. Please enter a valid credit card number'. 

Example down request extracted
```
=> "--- |-\n" +
"  <?xml version=\"1.0\" encoding=\"UTF-8\"?><env:Envelope xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:env=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"><env:Header><RequesterCredentials xmlns=\"urn:ebay:api:PayPalAPI\" xmlns:n1=\"urn:ebay:apis:eBLBaseComponents\" env:mustUnderstand=\"0\"><n1:Credentials><n1:Username>{hidden}/n1:Username><n1:Password>{hidden}</n1:Password><n1:Subject/><n1:Signature>{hidden}</n1:Signature></n1:Credentials></RequesterCredentials></env:Header><env:Body><DoDirectPaymentReq xmlns=\"urn:ebay:api:PayPalAPI\">\n" +
"    <DoDirectPaymentRequest xmlns:n2=\"urn:ebay:apis:eBLBaseComponents\">\n" +
"      <n2:Version>124</n2:Version>\n" +
"      <n2:DoDirectPaymentRequestDetails>\n" +
"        <n2:PaymentAction>Sale</n2:PaymentAction>\n" +
"        <n2:PaymentDetails>\n" +
"          <n2:OrderTotal currencyID=\"GBP\">19.60</n2:OrderTotal>\n" +
"          <n2:InvoiceID>R107015713-PEQRXT8I</n2:InvoiceID>\n" +
"          <n2:ShipToAddress>\n" +
"            <n2:Name>John Doe</n2:Name>\n" +
"            <n2:Street1>123 Division Street</n2:Street1>\n" +
"            <n2:Street2>Apt. #1</n2:Street2>\n" +
"            <n2:CityName>Chicago</n2:CityName>\n" +
"            <n2:StateOrProvince>IL</n2:StateOrProvince>\n" +
"            <n2:Country>US</n2:Country>\n" +
"            <n2:Phone>312-123-4567</n2:Phone>\n" +
"            <n2:PostalCode>60618</n2:PostalCode>\n" +
"          </n2:ShipToAddress>\n" +
"        </n2:PaymentDetails>\n" +
"        <n2:CreditCard>\n" +
"          <n2:CreditCardType>Visa</n2:CreditCardType>\n" +
"          <n2:CreditCardNumber/>\n" +
"          <n2:ExpMonth>11</n2:ExpMonth>\n" +
"          <n2:ExpYear>2019</n2:ExpYear>\n" +
"          <n2:CardOwner>\n" +
"            <n2:PayerName>\n" +
"              <n2:FirstName>John</n2:FirstName>\n" +
"              <n2:LastName>Doe</n2:LastName>\n" +
"            </n2:PayerName>\n" +
"            <n2:Payer>david.roy@cabbit.co.uk</n2:Payer>\n" +
"            <n2:Address>\n" +
"              <n2:Name>John Doe</n2:Name>\n" +
"              <n2:Street1>123 Billing Street</n2:Street1>\n" +
"              <n2:Street2>Apt. #1</n2:Street2>\n" +
"              <n2:CityName>Chicago</n2:CityName>\n" +
"              <n2:StateOrProvince>IL</n2:StateOrProvince>\n" +
"              <n2:Country>US</n2:Country>\n" +
"              <n2:Phone>312-123-4567</n2:Phone>\n" +
"              <n2:PostalCode>60618</n2:PostalCode>\n" +
"            </n2:Address>\n" +
"          </n2:CardOwner>\n" +
"        </n2:CreditCard>\n" +

```
Example response
```
Gateway Error
  --- !ruby/object:ActiveMerchant::Billing::Response
params:
  timestamp: '2017-09-04T16:23:28Z'
  ack: Failure
  correlation_id: 777b39cee98ae
  version: '124'
  build: '36082234'
  amount: '19.60'
  amount_currency_id: GBP
  message: This transaction cannot be processed. Please enter a valid credit card
    number and type.
  error_codes: '10527'
  Timestamp: '2017-09-04T16:23:28Z'
  Ack: Failure
  CorrelationID: 777b39cee98ae
  Errors:
    ShortMessage: Invalid Data
    LongMessage: This transaction cannot be processed. Please enter a valid credit
      card number and type.
    ErrorCode: '10527'
    SeverityCode: Error
  Version: '124'
  Build: '36082234'
  Amount: '19.60'
message: This transaction cannot be processed. Please enter a valid credit card number
  and type.
success: false
test: false
authorization: 
fraud_review: false
error_code: :processing_error
emv_authorization: 
avs_result:
  code: 
  message: 
  street_match: 
  postal_match: 
cvv_result:
  code: 
  message: 
```

```
[14] pry(#<ActiveMerchant::Billing::PaypalGateway>)> credit_card_or_referenced_id.number
=> nil
```
